name: Front Deployment with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:
    name: Docker Build & Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v3
      
      # Docker 이미지를 빌드하고 캐시합니다.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Docker login # Run before building the Docker image
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Docker build and push
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-react-app .
          docker push ${{ secrets.DOCKER_USERNAME }}/my-react-app
      
      # AWS에 접근하기 위한 권한을 설정합니다.
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CLOUD_AWS_CREDENTIALS_ACCESSKEY }}
          aws-secret-access-key: ${{ secrets.CLOUD_AWS_CREDENTIALS_SECRETKEY }}
          aws-region: ap-northeast-2

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CLOUD_AWS_HOST }}
          username: ${{ secrets.CLOUD_AWS_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest
            docker stop my-react-app || true
            docker rm my-react-app || true
            docker run -d -p 84:3000 --name my-react-app ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest